### ISSUE TITLE
do you need a jamovi icon?

### ISSUE THREAD

**Issue by dropmann** [OlafHaag/chocolatey-packages#10]
What format would you need?

**Comment by OlafHaag** [comment]
Yes. Guidelines for the icon can be found here: https://chocolatey.org/docs/create-packages#package-icon-guidelines.
Basically, at least 128x128 pixels with transparent background as PNG.

**Comment by dropmann** [comment]
![jamovi-128](https://cloud.githubusercontent.com/assets/11178513/25644409/13bca70e-2fe9-11e7-9ff6-14b8284b1764.png)

**Comment by dropmann** [comment]
This should do the job! thanks for your hard work :)
