### ISSUE TITLE
Chocolatey package for development snapshots of JabRef?

### ISSUE THREAD

**Issue by kmindi** [OlafHaag/chocolatey-packages#13]
It would be great, as the old JabRef 4.x has not seen recent releases, to have the development snapshots avialable via a chocolatey package, is that possible?

The latest builds are avialable here: http://builds.jabref.org/master/

The package could be marked as prerelase, so could only be installed in choco with `-pre`

**Comment by OlafHaag** [comment]
I had a short look and it seems doable using -pre and fix notation. But those are nightly builds, so there'd be a new pre-release each day. I have to check with the choco docs or community if that is appropiate behaviour for a package.
I'm not sure when I can find time to actually do this. So please be a bit patient or make a pull request.

**Comment by OlafHaag** [comment]
The 5.0 alpha was released and is available as a prerelease package on chocolatey now.
