### ISSUE TITLE
jamovi: Invalid nuspec file Version '' - using 0.0

### ISSUE THREAD

**Issue by OlafHaag** [OlafHaag/chocolatey-packages#15]
After changes to include different streams of jamovi this warning is thrown:
`Invalid nuspec file Version '' - using 0.0` when running update.ps1.

**Comment by Gootjes** [comment]
@OlafHaag 
I can't reproduce your issue unfortunately.

**Comment by OlafHaag** [comment]
yeah, sorry, I fixed it in the meantime. The json files were just missing.
