### ISSUE TITLE
jamovi: Get-FixVersion introduces extra 0's

### ISSUE THREAD

**Issue by Gootjes** [OlafHaag/chocolatey-packages#16]
The usage of fix version [here](https://github.com/OlafHaag/chocolatey-packages/blob/master/automatic/jamovi/update.ps1#L37) changes version `1.0.7.0` to `1.0.7.000`.
Which is technically not true, and it means users have to type `--version=1.0.7.000` instead of the more intuitive `--version=1.0.7.0` to get the right version. The normal `Get-Version` does not do this.

Is there a reason that I am unaware of doing this? Maybe it caused #15 .

**Comment by OlafHaag** [comment]
I agree. Should be more intuitive with the next jamovi updates.

**Comment by OlafHaag** [comment]
With Get-FixVersion there's always at leat 1 appended extra zero.
