### ISSUE TITLE
XNVIEWMP: 403 Forbidden

### ISSUE THREAD

**Issue by God-damnit-all** [OlafHaag/chocolatey-packages#26]
When trying to install or upgrade the xnviewmp package, a 403 forbidden error is thrown when trying to download the installer.

**Comment by OlafHaag** [comment]
Oh, wow, that just worked until yesterday. Now they block it.

**Comment by OlafHaag** [comment]
license states

> 3. Distribution
> 
>   * Freeware
>   
>     You are hereby licensed to make as many copies of the SOFTWARE as you wish and distribute it to anyone provided that all files are intact. You must distribute the install form of the SOFTWARE (not the files resulting of an installation). 

and also

> 6. Restrictions
>   
>   You may not distribute, rent, sub-license the SOFTWARE, except as expressly permitted in this License without prior written consent from Author. 

I guess that means I can bundle it with the chocopackage for future versions.

**Comment by God-damnit-all** [comment]
I went ahead and emailed them about it. It does concern me, since the changelog on the site is not usually up to date with the latest release, so there's not really a good way to know that there's even been an update.

I'll let you know what they say.

**Comment by OlafHaag** [comment]
Maybe your e-mail solved the issue. It's unblocked again.

**Comment by God-damnit-all** [comment]
> Maybe your e-mail solved the issue. It's unblocked again.

Huh, maybe. There wasn't a reply, but if it's been unblocked, then that's good enough for me.

**Comment by God-damnit-all** [comment]
Got an email today letting me know it's fixed. Sounds like it was unintended in the first place.
